meta:
  repo: "https://github.com/yourusername/dotfiles.git"
  branch: "main"
  local_path: "~/.dotfiles" # Customizable repo location

distro_files:
  .bash_aliases:
    arch: ".bash_aliases.arch"
    debian: ".bash_aliases.debian"

hooks:
  conflict_resolver: "meld"
  pre_sync: "echo 'hello world'"
  post_sync: "notify-send 'Dotfiles synced!'"
  pre_push: # pre push hook
  post_push: # post push hook
  pre_pull: # pre pull hook
  post_pull: # post pull hook
